### ISSUE TITLE
Cannot read property min of undefined

### ISSUE THREAD

**Issue by joshharington** [jscharting/jscharting-vue#2]
I am trying to integrate this graph with my data on a laravel backend. I am pulling the data in correct format from the demos / examples.

````
series: [
    {
        name: 'Series 1',
        points: [{x: <timestamp>, y: <number>}, {x: <timestamp>, y: <number>}, {x: <timestamp>, y: <number>}]
    },
    {
        name: 'Series 2',
        points: [{x: <timestamp>, y: <number>}, {x: <timestamp>, y: <number>}, {x: <timestamp>, y: <number>}]
    }
]
````

I have about 10 000 points that I am trying to load. The names pop up in the legend. But I get the error `Uncaught TypeError: Cannot read property 'min' of undefined` and it doesn't load any graph.

**Comment by arthurPuszynski** [comment]
Hello, I tried to replicate this issue with 10k points and two series but was not able to see this issue you mentioned. Can you please take a look at this example and see if you can replicate this issue, then send me the link?
https://codepen.io/jsblog/pen/afa6ad0c4bf146de75145b5191592bcc

With that we should be able to find and resolve the bug quickly.
Thank you.
